### ISSUE TITLE
Dosnt read potion Quest

### ISSUE THREAD

**Issue by ItzDuckk** [waktool/RankQuests#68] opened 2024-08-01 09:33 UTC
i have a "Use 8 Tier IV Potions" quest and it allways dosnt read them all i get in the logs is this
![image](https://github.com/user-attachments/assets/a3d8f04a-9ee6-45d2-a57b-45adcefa0b5b)

and it just dosnt continue in any way

**Comment by waktool** [comment] 2024-08-06 10:38
Duplicate of #65

**Closed** 2024-08-06 10:38 UTC
